// <auto-generated />
using System;
using System.Text.Json;
using Driftworld.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Driftworld.Data.Migrations
{
    [DbContext(typeof(DriftworldDbContext))]
    [Migration("20260428121014_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Driftworld.Data.Entities.Cycle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("closed_at");

                    b.Property<DateTime>("EndsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ends_at");

                    b.Property<DateTime>("StartsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("starts_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("Status")
                        .IsUnique()
                        .HasDatabaseName("ix_one_open_cycle")
                        .HasFilter("status = 'open'");

                    b.ToTable("cycles", null, t =>
                        {
                            t.HasCheckConstraint("ck_cycles_status", "status IN ('open','closed')");
                        });
                });

            modelBuilder.Entity("Driftworld.Data.Entities.Decision", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Choice")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("choice");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("CycleId")
                        .HasColumnType("integer")
                        .HasColumnName("cycle_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("CycleId")
                        .HasDatabaseName("ix_decisions_cycle");

                    b.HasIndex("UserId", "CycleId")
                        .IsUnique()
                        .HasDatabaseName("ux_decisions_user_cycle");

                    b.ToTable("decisions", (string)null);
                });

            modelBuilder.Entity("Driftworld.Data.Entities.Event", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("CycleId")
                        .HasColumnType("integer")
                        .HasColumnName("cycle_id");

                    b.Property<JsonDocument>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("CycleId", "Type")
                        .IsUnique()
                        .HasDatabaseName("ux_events_cycle_type");

                    b.ToTable("events", (string)null);
                });

            modelBuilder.Entity("Driftworld.Data.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Handle")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("handle");

                    b.Property<DateTime?>("LastSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at");

                    b.HasKey("Id");

                    b.HasIndex("Handle")
                        .IsUnique()
                        .HasDatabaseName("ix_users_handle");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Driftworld.Data.Entities.WorldState", b =>
                {
                    b.Property<int>("CycleId")
                        .HasColumnType("integer")
                        .HasColumnName("cycle_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<short>("Economy")
                        .HasColumnType("smallint")
                        .HasColumnName("economy");

                    b.Property<short>("Environment")
                        .HasColumnType("smallint")
                        .HasColumnName("environment");

                    b.Property<int>("Participants")
                        .HasColumnType("integer")
                        .HasColumnName("participants");

                    b.Property<short>("Stability")
                        .HasColumnType("smallint")
                        .HasColumnName("stability");

                    b.HasKey("CycleId");

                    b.ToTable("world_states", (string)null);
                });

            modelBuilder.Entity("Driftworld.Data.Entities.Decision", b =>
                {
                    b.HasOne("Driftworld.Data.Entities.Cycle", "Cycle")
                        .WithMany()
                        .HasForeignKey("CycleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Driftworld.Data.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cycle");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Driftworld.Data.Entities.Event", b =>
                {
                    b.HasOne("Driftworld.Data.Entities.Cycle", "Cycle")
                        .WithMany()
                        .HasForeignKey("CycleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cycle");
                });

            modelBuilder.Entity("Driftworld.Data.Entities.WorldState", b =>
                {
                    b.HasOne("Driftworld.Data.Entities.Cycle", "Cycle")
                        .WithOne()
                        .HasForeignKey("Driftworld.Data.Entities.WorldState", "CycleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cycle");
                });
#pragma warning restore 612, 618
        }
    }
}
